# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.srcs/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024.xci
# IP: The module: 'fifo_w256_128_r32_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.gen/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_128_r32_1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.gen/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_128_r32_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.gen/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_128_r32_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.srcs/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024.xci
# IP: The module: 'fifo_w256_128_r32_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.gen/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_128_r32_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.gen/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_128_r32_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/okolhe/OneDrive - purdue.edu/Academics/Purdue/Testing System/FPGA/Random/ADC_16Ch_Stream/ADC_16Ch_Stream.gen/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_128_r32_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
